version: '3'

volumes:
  mongodb:

services:
  mongo:
    hostname: mongo
    restart: always
    image: 'bitnami/mongodb:4.0'
    volumes:
      - mongodb:/bitnami
    ports:
      - 27017:27017
    network_mode: "host"


  bot:
    hostname: bot
    build:
      dockerfile: ./Dockerfile
      context: ./src/bot
    command: npm run bot
    restart: always
    volumes:
      - ./:/code
    network_mode: "host"