version: '3'


services:
  bot:
    hostname: bot
    build:
      dockerfile: ./Dockerfile
      context: ./src
    command: npm run bot:dev
    restart: always
    volumes:
      - ./:/code
    network_mode: "host"